source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'CJPAdController', '~> 1.7'
pod 'NSData+Base64', '~> 1.0'
pod 'xmlrpc', '~> 2.3'
pod 'AFNetworking', '~> 3.1'
pod 'TUSafariActivity', '~> 1.0'
pod 'DZNEmptyDataSet', '~> 1.8'
pod 'BGTableViewRowActionWithImage'